apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-project-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/devops-project-pv
