apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  selector:
    app: devops-project
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
