version: '3.8'

services:
  web:
    image: matheogonnet/devops-project-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
